name: MiniURL_dev
values:
  - key: baseUrl
    value: ''
  - key: token
    secret: true
  - key: ''
    value: ''
  - key: userId
    value: ''
  - key: username
    value: ''
  - key: nickname
    value: ''
  - key: accessToken
    value: ''
  - key: refreshToken
    value: ''
